# Generated by Django 3.2.3 on 2021-07-26 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=12)),
                ('board', models.CharField(max_length=60)),
                ('thread_id', models.IntegerField()),
                ('post_id', models.IntegerField()),
                ('author', models.CharField(max_length=180)),
                ('subject', models.CharField(max_length=150)),
                ('body', models.TextField()),
                ('timestamp', models.DateTimeField()),
                ('tripcode', models.CharField(default=None, max_length=30)),
                ('is_op', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddConstraint(
            model_name='post',
            constraint=models.UniqueConstraint(fields=('platform', 'board', 'post_id'), name='unique_post'),
        ),
    ]
