# Generated by Django 3.2.3 on 2021-07-27 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='links',
            field=models.JSONField(default={}),
        ),
    ]
