# Generated by Django 3.2.3 on 2021-06-03 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='id',
        ),
        migrations.AlterField(
            model_name='post',
            name='post_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
