# Generated by Django 3.2.3 on 2021-06-03 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20210603_0427'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_op',
            field=models.BooleanField(default=False),
        ),
    ]
