# Generated by Django 3.2.3 on 2021-08-04 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_drop'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='drop_no',
        ),
    ]
