# Generated by Django 3.2.3 on 2021-07-21 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_is_op'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tripcode',
            field=models.CharField(default=None, max_length=30),
        ),
    ]
