# Generated by Django 3.2.3 on 2021-08-05 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_remove_post_drop_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='reply_to',
        ),
    ]
