# Generated by Django 3.2.3 on 2021-07-28 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_post_search_vector'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='poster_hash',
            field=models.CharField(default='', max_length=12),
            preserve_default=False,
        ),
    ]
