# Generated by Django 3.2.3 on 2021-07-21 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_post_tripcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='board',
            field=models.CharField(default='', max_length=60),
            preserve_default=False,
        ),
    ]
