# Generated by Django 3.2.3 on 2021-08-05 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_remove_post_reply_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='replies',
            field=models.JSONField(default=dict),
        ),
    ]
