# Generated by Django 3.2.3 on 2021-08-05 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_post_replies'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapeJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=12)),
                ('board', models.CharField(max_length=60)),
                ('thread_id', models.IntegerField()),
                ('url', models.CharField(max_length=120)),
                ('error_count', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
    ]
