# Generated by Django 3.2.3 on 2021-08-06 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_scrapejob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapejob',
            name='url',
            field=models.CharField(max_length=120, unique=True),
        ),
        migrations.AddConstraint(
            model_name='scrapejob',
            constraint=models.UniqueConstraint(fields=('platform', 'board', 'thread_id'), name='unique_thread'),
        ),
    ]
