# Generated by Django 3.2.3 on 2021-07-29 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20210728_2200'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='drop_no',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
