# Generated by Django 3.2.3 on 2021-08-06 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_auto_20210806_0522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapejob',
            name='bounty',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
