# Generated by Django 3.2.3 on 2021-07-31 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_post_reply_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='reply_to',
        ),
        migrations.AddField(
            model_name='post',
            name='reply_to',
            field=models.ManyToManyField(blank=True, null=True, related_name='replies', to='posts.Post'),
        ),
    ]
