# Generated by Django 3.2.3 on 2021-08-07 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_alter_scrapejob_bounty'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scrapejob',
            options={'ordering': ['-bounty']},
        ),
        migrations.AddField(
            model_name='board',
            name='migrated_to_8kun',
            field=models.BooleanField(default=False),
        ),
    ]
