# Generated by Django 3.2.3 on 2021-08-09 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_post_body_html'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapejob',
            name='url',
            field=models.CharField(max_length=120),
        ),
    ]
