# Generated by Django 3.2.3 on 2021-08-09 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_alter_scrapejob_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapejob',
            name='in_progress',
            field=models.BooleanField(default=False),
        ),
    ]
