# Generated by Django 3.2.3 on 2021-08-04 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_auto_20210804_0923'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='post',
        #     name='board_rel',
        # ),
        # migrations.RemoveField(
        #     model_name='post',
        #     name='platform_rel',
        # ),
        migrations.AlterField(
            model_name='post',
            name='board_rel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='posts.board'),
        ),
        migrations.AlterField(
            model_name='post',
            name='platform_rel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='posts.platform'),
        ),
    ]
