# Generated by Django 3.2.3 on 2021-08-30 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_scrapejob_in_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapejob',
            name='job_type',
            field=models.CharField(choices=[('NEW', 'New'), ('REV', 'Revisit')], default='NEW', max_length=3),
        ),
    ]
