# Generated by Django 3.2.3 on 2021-08-04 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_auto_20210804_1023'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='post',
            constraint=models.UniqueConstraint(fields=('platform', 'board', 'post_id'), name='unique_post'),
        ),
    ]
