# Generated by Django 3.2.3 on 2021-12-08 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0016_redditpost_subreddit'),
    ]

    operations = [
        migrations.AddField(
            model_name='redditpost',
            name='thread_id',
            field=models.CharField(default=1234, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='redditpost',
            name='thread_slug',
            field=models.CharField(default='asdfhajsdfj', max_length=60),
            preserve_default=False,
        ),
    ]
