# Generated by Django 3.2.3 on 2021-12-08 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0017_auto_20211208_0348'),
    ]

    operations = [
        migrations.RenameField(
            model_name='redditpost',
            old_name='thread_id',
            new_name='thread_hash',
        ),
    ]
