# Generated by Django 3.2.3 on 2021-12-04 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0017_alter_redditpost_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redditpost',
            name='url',
            field=models.URLField(max_length=2000, null=True),
        ),
    ]
