# Generated by Django 3.2.3 on 2021-12-04 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0018_alter_redditpost_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redditpost',
            name='subject',
            field=models.CharField(max_length=400),
        ),
    ]
