# Generated by Django 3.2.3 on 2022-03-06 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0018_rename_thread_id_redditpost_thread_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='redditpost',
            name='platform',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='reddit_posts', to='posts.platform'),
            preserve_default=False,
        ),
    ]
