# Generated by Django 3.2.3 on 2022-03-20 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0019_redditpost_platform'),
    ]

    operations = [
        migrations.CreateModel(
            name='BBSPinkPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thread_id', models.IntegerField()),
                ('post_id', models.IntegerField()),
                ('author', models.CharField(max_length=180)),
                ('email', models.CharField(max_length=180, null=True)),
                ('poster_hash', models.CharField(max_length=12, null=True)),
                ('subject', models.CharField(max_length=150, null=True)),
                ('body', models.TextField()),
                ('timestamp', models.DateTimeField(null=True)),
                ('tripcode', models.CharField(default=None, max_length=30)),
                ('capcode', models.CharField(default=None, max_length=30)),
                ('is_op', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bbspink_posts', to='posts.board')),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bbspink_posts', to='posts.platform')),
            ],
        ),
    ]
