# Generated by Django 3.2.3 on 2022-03-20 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0021_auto_20220320_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textboardpost',
            name='capcode',
            field=models.CharField(default=None, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='textboardpost',
            name='tripcode',
            field=models.CharField(default=None, max_length=30, null=True),
        ),
    ]
