# Generated by Django 3.2.3 on 2022-06-26 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0024_post_hidden_by_dchan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='hidden_by_dchan',
        ),
    ]
